### ISSUE TITLE
Power BI Visuals not honoring format strings in 1500 CM model with Calculation Groups?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#380]
Hi guys, not sure yet if this is a Power BI, AAS or a Tabular Editor issue but we have found that our new 1500 cube with calculation groups is not behaving correctly in Power BI

Power BI Matrix/Table and Cards work correctly but all of the visuals (line/bar/pie etc) do not honour the format string 

e.g.  left is a table, right is a bar chart for the same Axis/measure
![image](https://user-images.githubusercontent.com/13693159/72059791-9999d680-32ca-11ea-94dd-f3de0f865d5e.png)

Other things I've noticed
- In Power BI we see every measure duplicated - the dupe holds the value for the format string and is always hidden

![image](https://user-images.githubusercontent.com/13693159/72059897-cea62900-32ca-11ea-9175-95d668bfc4ad.png)

- Excel pivot tables with live connection to the AAS work correctly

This model was built and deployed with Tabular Editor. Not sure if deploying with the MS tool might make any difference but that is one thing that I would like to try. 

Any other ideas on what might be causing this? Seems a pretty major issue that I would have thought Microsoft would have found during their dev/test...

**Comment by marcosqlbi** [comment]
I suggest you to open a ticket with Microsoft support as soon as possible.
For the first issue: it should depend on the visuals, for sure any custom visual should not work with dynamic format string, whereas the native Card visual should work correctly. I'm not sure about other visuals, but it is possible that there are visuals not working. I already raised the issue months ago with Microsoft, but as usual only tickets from customer can help to escalate the issue.

The second one (duplicated measures) is weird and I didn't notice it before. However, it's something that Microsoft has to fix in Power BI.

So my suggestion is to open two different tickets for the two issues, because they involve different teams within Microsoft and you will streamline the process this way. Please forward the ticket ID here when you have them - thanks!

**Comment by o-o00o-o** [comment]
Thanks Marco, thats a real shame and will prevent us from being able to release Calculation Groups at all. Surprising that it affects all our existing normal measures, but I guess they have had to change the whole format string system without any backward compatibility.

Card, Multirow card, Table and Matrix honour the format string. All the other standard visuals do not.

I guess custom visuals will be upgraded over time, or is the ability not yet provided to the custom visuals?

The first issue ticket number is 120010922001023
The second is less of an issue, but will post when we have that one

**Comment by dmarkle** [comment]
@o-o00o-o I would recommend holding off on deploying Calculation Groups/1500 models until at least CU2.  We are tracking a pretty nasty issue right now with tons of BLANK()s coming seemingly from out of nowhere, and MS is tracking CU2 for our fix in particular.  Thank you for filing your bugs; hopefully these issues shake out soon.  Calculation Groups are incredible.

**Comment by otykier** [comment]
Closing this as neither of these issues can be resolved within Tabular Editor (it's simply just using the TOM to apply the changes - you would get result by manually creating a calc group through TOM or through the use of a TMSL script). Please raise a ticket with Microsoft as suggested by Marco.

**Comment by o-o00o-o** [comment]
Just for visibility, the Power BI support team are now agreeing this is a known limitation and that it isn't planned to be developed until summer this year with no delivery ETA. 

This means that we (and I'm sure most existing cubes with Power BI reports against them) will be prevented from using calculation groups until them

I've created a community post with the details here. 

https://social.msdn.microsoft.com/Forums/en-US/3c71faf0-6613-4ed2-b34b-48961732f514/adding-a-single-calculation-group-to-aas-breaks-most-of-the-existing-company-power-bi-reports?forum=AzureAnalysisServices

@marcosqlbi I'm not sure if you or Alberto are able to help with your MS contacts to make sure this is put in front of the product owners - feels like a big oversight to me and I'm willing to be whoever decided on the priority of this wasn't aware that this would break existing reports that don't even use calculation groups.

**Comment by otykier** [comment]
Thanks for letting us know. Just out of curiosity, have you specified FormatStringExpressions for any of the Calc Items in your Calc Group? What happens if you specify [`SELECTEDMEASUREFORMATSTRING()`](https://dax.guide/selectedmeasureformatstring/) as the FormatStringExpression across all your calc items?

**Comment by o-o00o-o** [comment]
yeah we tried all of that when we initially saw the problem. It makes no difference, Power BI just isn't looking in the right place for these non-table visuals

In the basic example with a Date Calculations table with a "YOY %" then yes, you have to provide a format string to have this present the number as a % instead of the selectedmeasure's formatstring. 

As soon as you add a calculation group to a model, Analysis Services dramatically changes the model in how it provides the queries with the format string to apply. 

Suddenly every measure now has 2 measures with the same name (the measure itself and also the measure containing the format string) - you see it in both power bi and dax studio

![image](https://user-images.githubusercontent.com/13693159/74663665-1b1b3900-5194-11ea-9426-9be02bb8ef05.png)

So now the query tools need to write queries that return the format string for this specific context, rather than just being able to take the format string from the measure. 

It is a shame they didn't implement Format Strings in the same way they did for Data Types as this is provided as metadata with the resultset - although now you have to check per cell of results, again instead of being able to just get the datatype from the column definition.

**Comment by marcosqlbi** [comment]
The issue is bigger than I realized initially. I discovered this because custom visuals were not supporting dynamic format strings. But the fact that this breaks standard format string... well this is huge. I tried to raise awareness of the issue in MS pointing to the blog post in the Microsoft forum, let's see what happens in 1-2 days otherwise we'll escalate making it more visible in a blog post.

**Comment by otykier** [comment]
I guess the reason it’s not implemented as metadata is because you can have different format strings in the same column for different rows, whereas the data type is always the same across all rows for any given column. So they probably had to come up with a different implementation in which the format string is returned in a separate column.

**Comment by o-o00o-o** [comment]
@marcosqlbi Thanks for your support on this, Yes it is a massive issue as it breaks static format strings for normal measures. Appreciate anything that you can do to raise awareness about this. Considering most people using AAS/Cube are now using Power BI, it means that this great feature from the AAS team cannot be used by anyone due to this bug in Power BI. The problem was it was hidden as we did all our testing on our Calculation Groups using Matrix and Table visuals. Only when we released, immediately users were complaining that their existing charts with % measures were now showing as unintuitive decimal numbers without any format string applied.

@otykier Well, interestingly this is now the same for datatypes, As soon as you add a Calculation Group to a model, all measures have their datatype changed to variant and now the datatype can be changed for each cell rather than by each column for a similar reason as now the output of a Calculation Item being applied to a measure can change its data type. If you check the output of a DAX query (like using Invoke-AsCmd.ps1) it now indicates the output datatype per cell instead of for each column in the header area (as it used to). So I'm not sure why they didn't use this same method for Format Strings tbh.. perhaps there is a reason, or maybe two different approaches to the same problem.

**Comment by o-o00o-o** [comment]
The MS forum suggested I create a Idea so I did that here https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/39750307-format-strings-don-t-work-on-a-ssas-model-with-cal

**Comment by otykier** [comment]
The issue with measures changing their data types to variant is familiar. It happens when you have calculation items that do not follow certain patterns, such as `CALCULATE(SELECTEDMEASURE(), ...)` where the data type is guaranteed to not change. These patterns are unfortunately not documented, as far as I know. If you have any calc items that doesn’t follow this pattern, they have to decay all measure data types to variant.

As to the issue with format strings, here is some speculation on what I think is going on. Maybe @marcosqlbi knows the internals in more details.

Invoke-AsCmd actually uses XMLA to send the command to the model, meaning the returned result is a cellset, which explains why the data type is specified for each cell. On the other hand, when querying the model with an OLEDB connector, we get a flat dataset as the result, where its not possible to have differing data types per cell. I’m guessing Power BI uses the latter or another similar protocol that returns a flat dataset. You probably don’t see this issue with the format strings in Excel. That’s because Excel also uses XMLA, but since it uses XMLA with MDX it’s also able to get the format string per cell.

As to the fix: Microsoft either needs to make sure that all visuals query the hidden format string measures for every measure that is being used in the visual, as well as ensure that the visual actually applies that format string when rendering the value. Alternatively, they should query the model using XMLA and consume the returned cellset, but this probably requires much more effort.

**Comment by marcosqlbi** [comment]
The issue with the visuals is that are different types of visual, and depending on that, they manage variant or not. It seems this is an unfinished work and this is the behavior they probably have also when they connect to Multidimensional. The only thing we can do is to give more visibility and hope other big customers raise the issue with Microsoft.

**Comment by o-o00o-o** [comment]
@otykier well, the XMLA thing definately changed either due to switching to CM 1500 or by adding a Calculation Group to the Model as we have to modify our Automated Test tools. Previously we could use a datatype indicator in the header of the XMLA result but then we had to switch to cope with the datatype in each cell as the header just said variant now. Perhaps it was there before but we didn't need it as it was good enough to refer to the header one so we could tell numeric types for tolerance in our test tools. 

@marcosqlbi the support team did mention something about it being a known issue for MD.

So what you guys might be suggesting is that if I can stop the measures all changing to variant (perhaps with identifying that pattern) then perhaps we can work around this issue. 

I will definitely give that a go.. although it may not be easy or possible in our case for it to really do what we want..

**Comment by zenzeinet** [comment]
Hi folks,
I have the same issue here, and I have discovered something that might help in the struggle.
The thing is, in my case, I find the following:
- When Calc groups are added to the model, yes, the measures become variant. But this is not an issue by itself!...
- If *all* FormatStringExpression of *all* Calculation Items are empty, then the behaviour of measures is unchanged (at least in my testings) - the usual format strings of normal measures are properly shown in graphs, business as usual, all happy
- If afterwards, I add just one FormatStringExpression to ANY of the Calculation Items, (including SELECTEDMEASUREFORMATSTRING() or any other), then the bug arises and graphs in PowerBI do not respect their source formatting (matrix is OK as you have reported)

So in my case, it looks that the problem does not come from just 1500, or from adding calculation groups, but from adding a single FormatStringExpression  to the model. 
Therefore, in my case so far I am able to add Calculation Groups and Items without and issue to an existing model (phew!), but not use the custom format feature.

I hope this helps shed some light, and yes, Microsoft should solve this!

Best regards, Martin

**Comment by dmarkle** [comment]
Another breaking change I just found is that I have some format strings set
to the words "Short Date" in my model in TE.

That's all broken now; instead of giving me what I expect, my dates are
displaying as "S12orA DaAe" -- evidently all format strings need to be
explicit!

**Comment by o-o00o-o** [comment]
@zenzeinet thank you for sharing this! 

Actually this does provide an ok workaround so at least we can deploy the Calculation Groups to live and have our tests continue to work.

It just means that for the few calculation groups that require % format strings, these will still show as 0.01 etc. I can't see a good workaround for this, although I may want to try creating a new base measure that just presents as a % and see if this can work as without a format string it seems to automatically pick up the base measure format string.

**Comment by zenzeinet** [comment]
@o-o00o-o 
Yes, that is what we are currently doing. It is too bad, as the custom formating would be very nice in quite a few situations (and I cannot even add it selectively - it is all or nothing). Currency exchange, % measures, ratios, showing +/- simbols, custom dynamic units (eg showing Kb, Mb, Gb) etc. 

I'm hoping microsoft addresses this bug, and for us the wait is at least a few months, as we're running PBIRS which updates 3 times per year. Hopefully it should be done next release, but what a bummer they did not find this in testing. I personally found the bug too and was initially blaming myself for not finding the proper setting in a line graph, thinking "damn, I'm quite sure this was showing %s properly before..."

Best regards

**Comment by zenzeinet** [comment]
Hi,
It seems Microsoft has started the work:
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/39750307-format-strings-don-t-work-on-a-ssas-model-with-cal
Unfortunately it seems it will take them several months... if Marco, Daniel or anyone reading this could push them a little it would be great.
Best regards

**Comment by marcosqlbi** [comment]
We have no power to push it - it's just good it's now in their roadmap.

**Comment by zenzeinet** [comment]
Strange, the web page at 
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/39750307-format-strings-don-t-work-on-a-ssas-model-with-cal
has now dissapeared. Any of you know if this has been fixed in recent updates? I cannot test it until a new PBIRS version is released...
Thanks

**Comment by marcosqlbi** [comment]
They are working to solve the issue but I have no idea why they removed the item!

**Comment by otykier** [comment]
**Update:** A fix was just published to the July 2020 version of Power BI Desktop, where the dynamic formatting issue has been solved. Should be fixed in both the Windows Store version and the MSI.

**Comment by ravip27** [comment]
> **Update:** A fix was just published to the July 2020 version of Power BI Desktop, where the dynamic formatting issue has been solved. Should be fixed in both the Windows Store version and the MSI.

It doesn't look like it is fixed universally. The line chart works but column chart is still broken

**Comment by jainn4** [comment]
I have the August 2020 version of the desktop and the issue still hasn't resolved it seems. All my measures are coming out as "Variant"

**Comment by zenzeinet** [comment]
The measures have to be variant always when there are calculation groups.
That is not the issue.

The issue are visualizations not honoring the default formatting and/or the
calculation group format string.

PowerBI Matrix are OK. So are excel ones. The issue is with the remaining
visuals, eg line charts.

**Comment by vibesniper** [comment]
this issue has just tripped me up, and will have to revert to a model with no calc groups to honour existing reports! Noticed in Smart narrative visual (although not GA) can no longer render Text based measures because data type is variant.

any ideas on a fix from Microsoft?

**Comment by otykier** [comment]
@vibesniper which version of PBI Desktop are you using? Does this issue only affect the smart narrative visual?

**Comment by o-o00o-o** [comment]
I have to say I'm really frustrated with Microsoft's response to this and their commitment to the calculation item feature in general. 

I have had a support ticket open with them for over a year. They have told me it was solved for all visuals except for Guage), but it isn't. 

It might work now if you exclusively use Calculation Items and never use a measure on its own (but seriously.. who does that). Calculation Items are really quite limited on their own as often business users want to mix different combinations of calculation items for different measures - which ultimately still requires discrete measures today anyway. 

As soon as you set a single format string on a calculation group, all format strings defined on measures are ignored (except on table and matrixes)

You shouldn't need to remove your calc groups however as they could still be useful for code centralisation. You just can't set Format Strings on any Calculation Items and it should works OK. Depending on your use, most of the time your calculation items are probably returning the same format string as the base measure, however if you are trying to do something like % variance from absolute figures (YOY % etc.) then you run into difficult territory. Right now we just multiply that number by 100 in our calculation item and then usually provide a % measure with the correct format string that calls the Calculation Item (has to divide by 100 again) and expresses the sensibly formatted %.

I actually sent an update to my ticket earlier this week. I will continue to chase them to help them feel our pain.

Really feels like they have put this into either the "its too hard" or the "something else shiny over here" bucket

**Comment by vibesniper** [comment]
> @vibesniper which version of PBI Desktop are you using? Does this issue only affect the smart narrative visual?

March version (MS Store installation) - have just tested other visuals as text measure, Card, Multi-card and OKviz custom card states all work. So I may have been hasty in my issue, as I guess Smart Narrative is still in preview?

So maybe this more of a decision of using calc groups in model vs using visuals in preview. Just quite a shame after using calc groups/format strings to enhance the native visuals alongside smart narratives to get the most out of a report.

**Comment by marcosqlbi** [comment]
@o-o00o-o good points, I had a blog post about this topic and I wrongly thought Microsoft would have fixed the issue when they fixed the support in the first few visual, so I didn't complete it. I am putting it again in my todo list.

**Comment by o-o00o-o** [comment]
Thanks @marcosqlbi, I'm sure increasing the public visibility of this issue will help Microsoft prioritise this to unlock all the features of Calculation Groups

**Comment by o-o00o-o** [comment]
@vibesniper now try a column chart with a normal measure that has a format string (e.g. 0.00%) and notice that it now doesn't work

**Comment by Bregor-Mar-Rian** [comment]
Having just tried it with the latest versions of Power BI Desktop April 2021 and **Card with States** 1.6.8:

As soon as you set a Format String Expression e.g. "0.0%;-0.0%;0.0%" on any calculation item, 
measures with their own Format String set to e.g. 0.0%;-0.0%;0.0% all loose their percentage formatting.

Interestingly that now works fine in the standard KPI visual (I remember it wasn't the case several months ago). But still doesn't work in Card with States (which seems practically the only decent option for KPI targets/thresholds and small multiples).
It does seem like a major limitation. Or am I missing something?

**Comment by marcosqlbi** [comment]
The API for custom visuals still doesn't provide access to the feature. We have to wait Microsoft to release an API for custom visuals to support dynamic format strings, then wait until we implement it, then wait until the component is certified and published by Microsoft. However, we're still waiting for step 1.

**Comment by zenzeinet** [comment]
That's too bad, such a great feature as calc groups + calc format strings
still not totally matured (for pbi charts, although it works great on
excel). Hope they finish that soon, they ain't in a hurry it seems!

**Comment by vibesniper** [comment]
@o-o00o-o In my real model I thought most native visuals were behaving, and Card with States by OKviz.  In my experience it's just the smart narrative visual not being able to render text measures, which is more disappointing since it's still not working now GA in May update. Dummy file below: The calc groups that replace the original measure (in the smart narrative) with an integer work fine though. 

[Dummy pbix](https://nspccppschools-my.sharepoint.com/:u:/g/personal/patrick_mcmonagle_nspcc_org_uk/EWb9ItsLnflApeLh3vtSdvgBjuRqkkSILOv5WZa9rBLLuA?e=6M8P1X)

**Comment by InmetaHelge** [comment]
This issue is so stupid.. And dangerous because initial testing with matrices/tables does not reveal it.
Also, look at this: Bar chart without field in "axis" ignores formatstring. But if I put in a field, it is correctly formatted..
![image](https://user-images.githubusercontent.com/92156715/138291020-6f1e5af4-a4f4-4d27-bcab-0bc3a7bf0694.png)

**Comment by InmetaHelge** [comment]
@marcosqlbi , this article should contain a warning in the intro, in my opinion. 
https://www.sqlbi.com/articles/controlling-format-strings-in-calculation-groups/

Or do you consider this issue solved?

**Comment by PBI-David** [comment]
Just adding to the chat that I have encountered this today and it is still NOT fixed.
